apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "monad.fullname" .}}-scripts
data:
{{- $root := . }}
{{- range $path, $_ := .Files.Glob "scripts/*" }}
  {{ base $path }}: |
{{- tpl ($root.Files.Get $path) $root | nindent 4 }}
{{- end }}
