{{ if eq .Values.monitoring.enabled true }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{include "monad.fullname" .}}
spec:
  selector:
    matchLabels:
      {{- include "monad.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
    {{- with .Values.monitoring.endpoints }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
