# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  enable: false
  create: false
  secret: ""
  name: ghcr

# Shared image used by all Monad containers unless overridden per-component below.
image:
  name: ghcr.io/laminated-labs/monad
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

# This is to override the chart name.
nameOverride: ''
fullnameOverride: ''

# Number of replicas to run
replicaCount: 1

annotations: {}

node:
  name: ""
  network: testnet
  beneficiary: "0x0000000000000000000000000000000000000000"
  peers: []
  bootstrapPeers: []
  fullnodes: []
  remoteValidatorsURL: 'https://bucket.monadinfra.com/validators/testnet/validators.toml'
  remoteForkpointURL: 'https://bucket.monadinfra.com/forkpoint/testnet/forkpoint.toml'
  snapshots:
    enabled: true
    url: 'https://d1v5yevi7k4blc.cloudfront.net'
  terminationGracePeriodSeconds: 30

monlog:
  enable: false
  image:
    name: monlog
    tag: latest
    pullPolicy: IfNotPresent
  pollIntervalSeconds: 5

otel:
  # endpoint: https://otel-external.monadinfra.com:443
  endpoint: http://localhost:4317

# Configuration for the mpt container
mpt:
  image:
    name: ''
    pullPolicy: ''
    tag: ''

# Configuration for the main bft container
bft:
  image:
    name: ''
    pullPolicy: ''
    tag: ''
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  additionalArgs: []

# Configuration for the execution container
execution:
  image:
    name: ''
    pullPolicy: ''
    tag: ''
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  additionalArgs: []

# Configuration for the rpc container
rpc:
  image:
    name: ''
    pullPolicy: ''
    tag: ''
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  additionalArgs: []

# Used to set the secp and bls keys. Useful for testing. Should NOT be used with live keys.
secret:
  create: false
  name: monad-keys
  blsKey: ""
  secpKey: ""
  keystorePassword: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
  hostname: ""

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output StatefulSet definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output StatefulSet definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

extraInitContainers: []

nodeSelector: {}

tolerations: []

affinity: {}

# -- Array of extra K8s manifests to deploy
## Note: Supports use of custom Helm templates
extraObjects: []

# Configuration for monitoring
monitoring:
  enabled: false
  ports: []

testnet:
  chainId: 10143
  initPeers:
    - 02d84a0236ed911c8425dd78951ebbbbdfa7628781274b8db4423c67f65944102e
    - 0319bb3b694487c34ce350254e12462787e15ec9116efc1a905a0a9e4e180235bd
    - 02e5e6f1b70575c697e4e0a1d498d0f6206b5fcb9afe233a9fda90c700f6ad8d7e
    - 034c5dab059a4eb65136e739470869d561ecfd00af41acafce6b064d9bc9a1d1b6
    - 02645311ba0b9d4a55e36bb97abeaf944a7078c30b65caf19746b28a0ac2da22af
    - 036d09f684b77ae83c70cd1afe082aec114bfbf2732db7f0902c987862a2e4cc7b
    - 02cf1fa720a3887a7a6ba423874058c1e64b9dc54c57e6ee3d604d4563f945ee8e
    - 039a9eedcd27e0fcc74f454b346bfaff807ac9ee6f88fc0a5ecf00ecc9eb006431
  bootstrapPeers:
    - address: "64.31.54.6:8000"
      recordSeqNum: 0
      nameRecordSig: "3b9d7bb0395a93336a48bb0c2e410c50e777f4d88eb114bf925d580cd55431bc780d43fd75a46154d8105412480b25f350e4ceffea7a17ea42b351ba8374741500"
      pubkey: "02d84a0236ed911c8425dd78951ebbbbdfa7628781274b8db4423c67f65944102e"
    - address: "64.31.29.227:8000"
      recordSeqNum: 0
      nameRecordSig: "c8d537fde7ff3a713c0f5f82841a55910dfd784252f4c92a931e3ae67c4c6bcc08d53a9acd155f4591fd3011ef15da7264520a46809d03c3992c53ddca84208200"
      pubkey: "0319bb3b694487c34ce350254e12462787e15ec9116efc1a905a0a9e4e180235bd"
    - address: "188.214.131.19:8000"
      recordSeqNum: 0
      nameRecordSig: "75be548f996f85d733b322ffb92d4fba9dbc2bffe0c8ac7440a83652bedc9f93084f2c0121727ba8b9157ff5f4aea74092e1ec00fad5f9c9846f12a3b892f4d500"
      pubkey: "02e5e6f1b70575c697e4e0a1d498d0f6206b5fcb9afe233a9fda90c700f6ad8d7e"
    - address: "64.31.27.239:8000"
      recordSeqNum: 0
      nameRecordSig: "66bdf860b833b65f92b5376f197b513775fc832f5dc8cd00278ad6c74dca19865e537d0796f3dd67f717bf26468b11b9aefb41279fe326a7c5b19d56324a416801"
      pubkey: "034c5dab059a4eb65136e739470869d561ecfd00af41acafce6b064d9bc9a1d1b6"
    - address: "64.31.18.153:8000"
      recordSeqNum: 0
      nameRecordSig: "792235c5b66bcfab0165e821eca86319662cc5f2f941f92468767ee419df3c7e06f4ecba66826174d4f218d8719ef8c5141bbe5a3909c5a5e0e05e0b101aa1b400"
      pubkey: "02645311ba0b9d4a55e36bb97abeaf944a7078c30b65caf19746b28a0ac2da22af"
    - address: "64.130.56.117:8000"
      recordSeqNum: 0
      nameRecordSig: "7af3c226e710ab938f3a696d228bb9c6a45195771730e8cd7e1d8a471999fe7168371e50783f318d6febd9ab96daee69a0199533f42227b6d889398f8228af6501"
      pubkey: "036d09f684b77ae83c70cd1afe082aec114bfbf2732db7f0902c987862a2e4cc7b"
    - address: "185.189.44.231:8000"
      recordSeqNum: 0
      nameRecordSig: "da63874881cc1b89b234303acf6c737ef3d5948b34a72b74acbdf77ccbba710e7b4e77128ab2c5e90d5396cea786b23f732af52c742b95d90b19652c91c9700501"
      pubkey: "02cf1fa720a3887a7a6ba423874058c1e64b9dc54c57e6ee3d604d4563f945ee8e"
    - address: "185.150.190.139:8000"
      recordSeqNum: 0
      nameRecordSig: "fb924c12d4c95d9e0ab93d1241eabb834e1a3b4f6fe2c8c9ce31924ee253b9a23b352f8b5cfe4287f13d04f79c2ed2195177f555df1d5583800480df03ce903c01"
      pubkey: "039a9eedcd27e0fcc74f454b346bfaff807ac9ee6f88fc0a5ecf00ecc9eb006431"

mainnet:
  chainId: 143
  initPeers:
    - 037d1cbb43ffc35b540f5175cf366f5f5b5ee1c578ce493e5f689856da148f1cba
    - 02b74a25df4a04bf3fda28a8460946e1cc097adfe0f3851a67546ca328a052020e
    - 039bed2d57eb4140967b3a114594f046252fd781dba383d8ebcafac1988b7908f0
    - 02a7dd4717c55010da5b49fde4515dd1932e138c3b34360d34a9e112e5269eefca
    - 0267695371b9a65a2f3ad8324e15f09be7322c1678e5ae36aca277d4eb85a2c5ed
    - 024ed4df9c6b174ec5eaf9b1d937cf9ce69581aacfd0581f54793b3c13db69757d
    - 03f9e716c905b1d18ef97ada135799bd885b8c4bf24b01acc9964564cdee898527
    - 032760f4b5ce58fd6d4c952a1bfcd44bf315a2a178614700ed9e95cd42bbdb1bf6
  bootstrapPeers:
    - address: "64.31.29.190:8000"
      recordSeqNum: 0
      nameRecordSig: "b6d059ef48caac2aa3041c772dc0ec1a9257777ffd092bc9f09a3799d016decf52978e68d004907bf37675a87962521e2f1b849a950ef5d77b21d5616f5f078800"
      pubkey: "037d1cbb43ffc35b540f5175cf366f5f5b5ee1c578ce493e5f689856da148f1cba"
    - address: "64.31.53.173:8000"
      recordSeqNum: 0
      nameRecordSig: "4fabe57037e753b0d07fab771ba163d3f31991c99682a4d39cdbc9f317abc0ff1e5a5363bf620b03e081f70c1235667b9225a3ae816a677de6a5837f0600155c00"
      pubkey: "02b74a25df4a04bf3fda28a8460946e1cc097adfe0f3851a67546ca328a052020e"
    - address: "208.115.197.25:8000"
      recordSeqNum: 0
      nameRecordSig: "d7a36bad541a8de3fd283d153854ad3925950855349ccfa7a26d063fcd23492f26ea21a8f984fe76ca5c2ba01ff968f89696379512ef5ba1554b65ef24036f2201"
      pubkey: "039bed2d57eb4140967b3a114594f046252fd781dba383d8ebcafac1988b7908f0"
    - address: "64.130.52.235:8000"
      recordSeqNum: 0
      nameRecordSig: "257aa33045a866840a0d766ae3601cf807ca31a197ea3a1bfbcbfc76958860fa146239b60739928377bfc2ec279a84eff620e72bdac984a81c4a4cc9e2ecafa200"
      pubkey: "02a7dd4717c55010da5b49fde4515dd1932e138c3b34360d34a9e112e5269eefca"
    - address: "64.130.56.50:8000"
      recordSeqNum: 0
      nameRecordSig: "6c556b2b80e1623063aea46b47b502268faa3b722de376e3325961a21acc6739113ee23273322e5c9b0c2d3f746514f6d46250f373b9f5acb483c9f6763ac81f01"
      pubkey: "0267695371b9a65a2f3ad8324e15f09be7322c1678e5ae36aca277d4eb85a2c5ed"
    - address: "64.130.49.148:8000"
      recordSeqNum: 0
      nameRecordSig: "8d99cbc2731db8378cd7907ac7be7dd215af1416044a2a5cfc4551b043f4e0574e29de32cfc1004f1dc7f7ece5d6d83d335edb3ae5ea4ff56c887a0e03b9d67a00"
      pubkey: "024ed4df9c6b174ec5eaf9b1d937cf9ce69581aacfd0581f54793b3c13db69757d"
    - address: "69.162.93.53:8000"
      recordSeqNum: 0
      nameRecordSig: "8cac5dbe1703645b9c0136e199fd382387e86e4b6b4d12295c57dd36e51be4985091c92d661e5d4ad935edc23c5f77ee9a653b3002a1501705ab9c43b9f73aef00"
      pubkey: "03f9e716c905b1d18ef97ada135799bd885b8c4bf24b01acc9964564cdee898527"
    - address: "185.189.46.19:8000"
      recordSeqNum: 0
      nameRecordSig: "a32840063f51dde1fbaaef8c12e0f963d873a081c21d33d6c86275a91877f97516e51e8e98aba423f0b699f2968f68aef250b3cf9a7f34f9e63a770ebfb8db3c01"
      pubkey: "032760f4b5ce58fd6d4c952a1bfcd44bf315a2a178614700ed9e95cd42bbdb1bf6"
