# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets:
  enable: true
  create: true
  secret: ""
  name: categoryxyz

# This is to override the chart name.
nameOverride: ''
fullnameOverride: ''

isFullNode: false

# Number of replicas to run
replicaCount: 1

annotations: {}

node:
  name: ""
  network: testnet
  beneficiary: "0x0000000000000000000000000000000000000000"
  peers: []
  fullnodes: []
  remoteValidatorsURL: 'https://bucket.monadinfra.com/validators/testnet/validators.toml'
  remoteForkpointURL: 'https://bucket.monadinfra.com/forkpoint/testnet/forkpoint.toml'
  snapshots:
    enabled: true
    url: 'https://d1v5yevi7k4blc.cloudfront.net'
  terminationGracePeriodSeconds:

otel:
  # endpoint: https://otel-external.monadinfra.com:443
  endpoint: http://localhost:4317

# Configuration for the mpt container
mpt:
  image:
    name: categoryxyz/monad-mpt
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ''

# Configuration for the main bft container
bft:
  image:
    name: categoryxyz/monad-bft
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ''
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  additionalArgs: []

# Configuration for the execution container
execution:
  image:
    name: categoryxyz/monad-execution
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ''
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  additionalArgs: []

# Configuration for the rpc container
rpc:
  image:
    name: categoryxyz/monad-rpc
    # This sets the pull policy for images.
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ''
  livenessProbe: {}
  readinessProbe: {}
  startupProbe: {}
  additionalArgs: []

# Used to set the secp and bls keys. Useful for testing. Should NOT be used with live keys.
secret:
  create: false
  name: monad-keys
  blsKey: ""
  secpKey: ""
  keystorePassword: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ''

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 8080
  hostname: ""

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Additional volumes on the output StatefulSet definition.
extraVolumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output StatefulSet definition.
extraVolumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

extraInitContainers: []

nodeSelector: {}

tolerations: []

affinity: {}

# -- Array of extra K8s manifests to deploy
## Note: Supports use of custom Helm templates
extraObjects: []

# Configuration for monitoring
monitoring:
  enabled: false
  ports: []

